logging:
  level:
    openmart:
      apiserver:
        api: DEBUG
  path: "/tank0/logs"

management:
  endpoints:
    web:
      exposure:
        include: "refresh, env"

---
spring:
  profiles: stg,prd

logging:
  level:
    openmart:
      apiserver:
        api: ERROR
  path: "/home/ec2-user/tank0/logs"
