logging:
  level:
    openmart:
      apiserver:
        api: ERROR
  path: "/home/ec2-user/tank0/logs"
  
#  level:
#    root: error  
  
#spring:
#  resources:
#    static-locations:
#    - /swagger/

management:
  endpoints:
    web:
      exposure:
        include: "refresh, env, metrics"
