logging:
  level:
    openmart:
      apiserver:
        api: DEBUG
  #path: "/home/ec2-user/tank0/logs"
  path: "/tank0/logs"
#  level:
#    root: error  
  
#spring:
#  resources:
#    static-locations:
#    - /swagger/

management:
  endpoints:
    web:
      exposure:
        include: refresh, env
