
fileName: open-mart-api.yml

FIXED_HOLIDAYS_INFO: 매월 둘째주 일요일, 넷째주 일요일 (05월10일, 05월24일) - local, dev
API_RADIUS: 20000

---
spring:
  profiles: imac

COSTCO_FILE_PATH: /Users/sungjun.kim/tank0/holidays/costco.json
EMART_FILE_PATH: /Users/sungjun.kim/tank0/holidays/emart.json
HOMEPLUS_FILE_PATH: /Users/sungjun.kim/tank0/holidays/homeplus.json
LOTTEMART_FILE_PATH: /Users/sungjun.kim/tank0/holidays/lottemart.json

---
spring:
  profiles: macbook
  
COSTCO_FILE_PATH: /tank0/holidays/costco.json
EMART_FILE_PATH: /tank0/holidays/emart.json
HOMEPLUS_FILE_PATH: /tank0/holidays/homeplus.json
LOTTEMART_FILE_PATH: /tank0/holidays/lottemart.json

---
spring:
  profiles: stg,prd

FIXED_HOLIDAYS_INFO: 매월 둘째주 일요일, 넷째주 일요일 (05월10일, 05월24일)

COSTCO_FILE_PATH: /home/ec2-user/tank0/holidays/costco.json
EMART_FILE_PATH: /home/ec2-user/tank0/holidays/emart.json
HOMEPLUS_FILE_PATH: /home/ec2-user/tank0/holidays/homeplus.json
LOTTEMART_FILE_PATH: /home/ec2-user/tank0/holidays/lottemart.json
